#server:
#
#  port: 8082
#  session:
#    cookie:
#      name: OAUTH2SESSION
##  context-path: /eureka-zuul
##  tomcat:
##    uri-encoding: UTF-8
#spring:
#  application:
#    name: eureka-oauth2
#  profiles:
#    active: default

#  main:
#    banner-mode: "off"
#    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#  security:
#    basic:
#      enabled: false
#      user:
#        name: admin
#        password: admin

# eureka consumer消费者
#eureka:
#  client:
#    service-url:
#      defaultZone: http://admin:admin@zw-pc3-pc:8983/eureka/
#zuul:
#  routes:
#    eureka-provider:
#      path: /provider/**
#      serviceId: eureka-provider
#    eureka-consumer:
#      path: /consumer/**
#      serviceId: eureka-consumer
## eureka集群（服务注册与发现）
#eureka:
##  service:
##    enable-self-preservation: false
#  instance:
#    # 使用ip作为注册服务名称
##    preferIpAddress: true
#    hostname: eureka-server
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-server2:8982/eureka/
#    register-with-eureka: true
#    fetch-registry: true

## 单个eureka（服务注册与发现）
#eureka:
#  client:
#    # 不注册自己
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      # eureka.client.serviceUrl.defaultZone默认是http://localhost:8761/eureka/，需要配置eureka.client.serviceUrl.defaultZone覆盖默认
#      defaultZone: http://127.0.0.1:8983/eureka/

# 开启基于Feign的融断
#feign:
#  hystrix:
#    enabled: true

#安全配置
#security:
#  basic:
#    enabled: false
#  user:
#    name: admin
#    password: admin
#  #oauth2配置
#  oauth2:
#    resource:
#      filter-order: 3
#    loginSubmit:
#      secretKey: thinkgem,jeesite,com