adminPath: a
server:
  port: 8088
  servlet:
    context-path: /codegen
    encoding:
      charset: UTF-8
spring:
  application:
    name: codegen
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappings/**/*Dao.xml
  global-config:
    logic-not-delete-value: 0
    logic-delete-value: 1
beetl:
  enabled: true
  suffix: html
beetlsql:
  enabled: false
shiro:
  # 登录
  loginUrl: /${adminPath}/login
  # 登录页面
  redirectUrl: /${adminPath}/login
  # 无权限时跳转的url
  unauthorizedUrl: /${adminPath}/role
  # 验证成功后跳转路径
  successUrl: /${adminPath}/index
  # 授权过滤定义
  filterChainDefinitions: |
    /${adminPath}/logout = logout
    /${adminPath}/login = authc
    /${adminPath}/toLogin = anon
    /${adminPath}/role = anon
    /${adminPath}/** = user
  globalSessionTimeout: 1800000
  app:
    sessionTimeOut: -1
  web:
    sessionTimeOut: 1800000