server:
  port: 8088
  servlet:
    context-path: /codegen
    encoding:
      charset: UTF-8
spring:
  application:
    name: codegen
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappings/**/*Dao.xml
  global-config:
    logic-not-delete-value: 0
    logic-delete-value: 1
beetl:
  enabled: true
  suffix: html
beetl-beetlsql:
  dev: true