adminPath: a
server:
  port: 8088
  servlet:
    context-path: /codegen
    encoding:
      charset: UTF-8
spring:
  application:
    name: codegen
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappings/**/*Dao.xml
  global-config:
    logic-not-delete-value: 0
    logic-delete-value: 1
beetl:
  enabled: true
  suffix: html
beetlsql:
  enabled: false
shiro:
  # 登录
  loginUrl: /${adminPath}/user/login
  # 登录页面
  redirectUrl: /${adminPath}/user/toLogin
  # 无权限时跳转的url
  unauthorizedUrl: /${adminPath}/user/role
  # 授权过滤定义
  filterChainDefinitions: |
    /${adminPath}/user/logout = logout
    /${adminPath}/user/login = authc
    /${adminPath}/user/toLogin = anon
    /${adminPath}/user/role = anon
    /${adminPath}/** = user